### ISSUE TITLE
EXCEPTION: noUiSlider (9.2.0): 'start' is required.

### ISSUE THREAD

**Issue by Ellipizle** [tb/ng2-nouislider#48]
```javascript
<nouislider [connect]="true" [min]="field.min" [max]="field.max" [step]="1" #range
(ngModelChange)="integerField($event,range,field.name)"></nouislider>
```

this gives  ORIGINAL EXCEPTION: noUiSlider (9.2.0): 'start' is required.

**Comment by Ellipizle** [comment]
my mistake, have to fix the ngmodel

**Comment by Rachana-Mahajan** [comment]
How were you able to fix this issue? 
I am using webpacks, and have imported the 'NouisliderModule' in app.module.ts. 
Further, I have declared it in imports section. 
My html contains:
**<nouislider [connect]="true" [min]="0" [max]="10" [step]="1" #range></nouislider>**

But I get the following error:
*************************************************************************************************************
EXCEPTION: Error in ./AppComponent class AppComponent - inline template:4:61 caused by: noUiSlider (9.2.0): 'start' is required.
ErrorHandler.handleError @ error_handler.js:54
(anonymous) @ application_ref.js:261
webpackJsonp.553.ZoneDelegate.invoke @ zone.js:334
onInvoke @ ng_zone.js:273
webpackJsonp.553.ZoneDelegate.invoke @ zone.js:333
webpackJsonp.553.Zone.run @ zone.js:126
(anonymous) @ zone.js:713
webpackJsonp.553.ZoneDelegate.invokeTask @ zone.js:367
onInvokeTask @ ng_zone.js:264
webpackJsonp.553.ZoneDelegate.invokeTask @ zone.js:366
webpackJsonp.553.Zone.runTask @ zone.js:166
drainMicroTaskQueue @ zone.js:546
error_handler.js:56 ORIGINAL EXCEPTION: noUiSlider (9.2.0): 'start' is required.
ErrorHandler.handleError @ error_handler.js:56
(anonymous) @ application_ref.js:261
webpackJsonp.553.ZoneDelegate.invoke @ zone.js:334
onInvoke @ ng_zone.js:273
webpackJsonp.553.ZoneDelegate.invoke @ zone.js:333
webpackJsonp.553.Zone.run @ zone.js:126
(anonymous) @ zone.js:713
webpackJsonp.553.ZoneDelegate.invokeTask @ zone.js:367
onInvokeTask @ ng_zone.js:264
webpackJsonp.553.ZoneDelegate.invokeTask @ zone.js:366
webpackJsonp.553.Zone.runTask @ zone.js:166
drainMicroTaskQueue @ zone.js:546
error_handler.js:59 ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:59
(anonymous) @ application_ref.js:261
webpackJsonp.553.ZoneDelegate.invoke @ zone.js:334
onInvoke @ ng_zone.js:273
webpackJsonp.553.ZoneDelegate.invoke @ zone.js:333
webpackJsonp.553.Zone.run @ zone.js:126
(anonymous) @ zone.js:713
webpackJsonp.553.ZoneDelegate.invokeTask @ zone.js:367
onInvokeTask @ ng_zone.js:264
webpackJsonp.553.ZoneDelegate.invokeTask @ zone.js:366
webpackJsonp.553.Zone.runTask @ zone.js:166
drainMicroTaskQueue @ zone.js:546
error_handler.js:60 Error: noUiSlider (9.2.0): 'start' is required.
    at http://localhost:4000/vendor.bundle.js:78451:12 [angular]
    at Array.forEach (native) [angular]
    at testOptions (http://localhost:4000/vendor.bundle.js:78445:22) [angular]
    at Object.initialize [as create] (http://localhost:4000/vendor.bundle.js:79724:17) [angular]
    at NouisliderComponent.ngOnInit (http://localhost:4000/vendor.bundle.js:77385:34) [angular]
    at Wrapper_NouisliderComponent.ngDoCheck (/NouisliderModule/NouisliderComponent/wrapper.ngfactory.js:180:53) [angular]
    at CompiledTemplate.proxyViewClass.View_AppComponent0.detectChangesInternal (/AppModule/AppComponent/component.ngfactory.js:79:33) [angular]
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4000/vendor.bundle.js:72686:14) [angular]
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4000/vendor.bundle.js:72881:44) [angular]
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:4000/vendor.bundle.js:72671:18) [angular]
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.detectChangesInternal (/AppModule/AppComponent/host.ngfactory.js:29:19) [angular]
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4000/vendor.bundle.js:72686:14) [angular]
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4000/vendor.bundle.js:72881:44) [angular]
*************************************************************************************************************

**Comment by usamedin** [comment]
hi @Rachana-Mahajan  the model is not correct 
someRange: [ 2, 10 ]; instead use "="
someRange= [ 2, 10 ];

**Comment by Rachana-Mahajan** [comment]
Exactly!!!!
That was what was wrong!
Thanks a lot for the solution! +1

**Comment by Rachana-Mahajan** [comment]
I was able to fix this issue by properly decalring the someRange:
Instead of  **someRange: [ 2, 10 ];**, we should declare:  **someRange=[ 2, 10 ];**
